const express = require("express");
const router = express.Router();
const healthRoutes = require("./health.routes");
const authRoutes = require("./auth.routes");
const dashboardRoutes = require("./dashboard.routes");
const mapRoutes = require("./map.routes");
const providerRoutes = require("./provider.routes");
const chatRoutes = require("./chat.routes");
const agentRoutes = require("./agent.routes");
const riskRoutes = require("./risk.routes");
const explainRoutes = require("./explain.routes");
const geofenceRoutes = require("./geofence.routes");
const routeRoutes = require("./route.routes");
const alertRoutes = require("./alert.routes");
const traceRoutes = require("./trace.routes");
const authMiddleware = require("../middleware/auth.middleware");

router.use("/", healthRoutes);
router.use("/auth", authRoutes);
router.use("/dashboard", authMiddleware, dashboardRoutes);
router.use("/map", authMiddleware, mapRoutes);
router.use("/chat", authMiddleware, chatRoutes);
router.use("/agents", authMiddleware, agentRoutes);
router.use("/risk", authMiddleware, riskRoutes);
router.use("/explain", authMiddleware, explainRoutes);
router.use("/geofence", authMiddleware, geofenceRoutes);
router.use("/routes", authMiddleware, routeRoutes);
router.use("/alerts", authMiddleware, alertRoutes);
router.use("/traces", authMiddleware, traceRoutes);
router.use("/", authMiddleware, providerRoutes);

module.exports = router;
